window.JITA_MISSIONS = [
  {
    id: 1,
    title: 'Misión de Esperanza en Guatemala',
    location: 'Guatemala City, Guatemala',
    date: '15-22 Marzo 2024',
    participants: 25,
    country: 'guatemala',
    status: 'completada',
    category: 'medica',
    description: 'Compartimos el evangelio, distribuimos biblias y canastas de alimentos, mientras brindamos atención médica gratuita a comunidades rurales.',
    detailedDescription: 'Esta misión fue un testimonio poderoso del amor de Dios en acción. Priorizamos compartir el evangelio y distribuir biblias a cada familia, mientras brindábamos atención médica gratuita y entregábamos canastas de alimentos.',
    impact: '500+ personas atendidas, 80 decisiones por Cristo',
    objectives: [
      'Compartir el evangelio y distribuir biblias',
      'Entregar canastas de alimentos',
      'Brindar atención médica gratuita',
      'Entregar juguetes a niños',
      'Establecer relaciones con líderes locales',
    ],
    achievements: [
      'Compartimos el evangelio con más de 800 personas',
      'Distribuimos 500+ biblias',
      'Entregamos 450 canastas de alimentos',
      '80 personas entregaron su vida a Cristo',
    ],
    team: [
      { name: 'Dr. Carlos Mendoza', role: 'Médico Líder' },
      { name: 'Pastor Luis Herrera', role: 'Líder Evangelístico' },
    ],
  },
  {
    id: 2,
    title: 'Misión Edifica en Honduras',
    location: 'Tegucigalpa, Honduras',
    date: '10-17 Abril 2024',
    participants: 30,
    country: 'honduras',
    status: 'completada',
    category: 'construccion',
    description: 'Compartimos el evangelio, distribuimos biblias y útiles escolares, entregamos juguetes y canastas de alimentos.',
    detailedDescription: 'Misión transformadora donde compartimos la palabra de Dios mientras construíamos aulas para el futuro.',
    impact: '150 niños recibieron la palabra de Dios, 120 familias bendecidas',
    objectives: [
      'Compartir el evangelio y distribuir biblias',
      'Entregar canastas de alimentos a familias',
      'Construir 2 aulas escolares',
    ],
    achievements: [
      'Distribuimos 350 biblias',
      'Entregamos 280 canastas de alimentos',
      'Completamos 2 aulas con capacidad para 75 niños',
    ],
  },
  {
    id: 3,
    title: 'Misión Pan de Vida en Colombia',
    location: 'Medellín, Colombia',
    date: '5-12 Mayo 2024',
    participants: 20,
    country: 'colombia',
    status: 'planificada',
    category: 'alimentaria',
    description: 'Llevamos la palabra de Dios a las calles, distribuimos biblias, entregamos canastas de alimentos y preparamos comidas para familias necesitadas.',
    detailedDescription: 'Una misión integral que prioriza compartir la palabra de Dios y el alimento espiritual del evangelio, junto con ayuda alimentaria práctica.',
    impact: 'Meta: 1000+ familias escucharán el evangelio y recibirán alimento',
    objectives: [
      'Compartir el evangelio a 1000+ familias',
      'Entregar canastas de alimentos completas',
      'Preparar desayunos y almuerzos en comedores',
    ],
  },
  {
    id: 4,
    title: 'Misión Fortaleza en Perú',
    location: 'Lima, Perú',
    date: '20-27 Junio 2024',
    participants: 15,
    country: 'peru',
    status: 'planificada',
    category: 'educativa',
    description: 'Compartimos enseñanzas bíblicas profundas, distribuimos biblias y apoyamos a pastores locales con la palabra de Dios.',
    detailedDescription: 'Capacitación integral a líderes locales en la palabra de Dios y el ministerio práctico.',
    impact: 'Meta: 50 líderes fortalecidos en la palabra de Dios',
  },
];
